config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'like/index'
  get 'like/show'
  get 'like/update'
  get 'like/destroy'
  get 'like/new'
  get 'like/edit'
  root to: 'home#index'
  resources :home
  resources :welcome
  resources :team
  resources :contact
  resources :gossip
  resources :profile
  resources :city
  resources :gossip do
    resources :comment
  end
  resources :session, only: %i[new create destroy]

  # ressources :like
  put '/gossip/:id/like', to: 'gossip#like', as: 'like'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def liked?(user)
    !!likes.find { |like| like.user_id == user.id }
  end
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  has_many :users
  validates :name, presence: true
  validates :zip_code, length: { is: 5 }, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/dm.rb
# frozen_string_literal: true

class Dm < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :join_user_dms
  has_many :recipients, class_name: 'User', through: :join_user_dms

  validates :content, length: { maximum: 140 }, presence: true
end

app/models/gossip.rb
# frozen_string_literal: true

class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :comments
  has_many :likes

  validates :title, length: { minimum: 3, maximum: 14 }, presence: true
  validates :content, presence: true
end

app/models/join_tag_gossip.rb
# frozen_string_literal: true

class JoinTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/join_user_dm.rb
# frozen_string_literal: true

class JoinUserDm < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :dm
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :user
  validates :user_id, uniqueness: { scope: :gossip_id }
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips

  validates :title, length: { minimum: 3, maximum: 14 }, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'Dm'
  has_many :join_user_dms
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'Dm', through: :join_user_dms
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
  has_many :comments
  has_many :likes

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, length: { maximum: 140 }, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :age, presence: true

  def name_with_initial
    "#{first_name} #{last_name}"
  end

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
  
end

app/controllers/gossip_controller.rb
# frozen_string_literal: true

class GossipController < ApplicationController
  before_action :authenticate_user, only: %i[new create]
  before_action :check_user, only: %i[edit update destroy]

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.where(gossip_id: params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:gossip_title], content: params[:gossip_content], user_id: session[:user_id])
    if @gossip.save
      redirect_to gossip_path(@gossip.id), success: 'Gossip validé !'
    else
      flash.now[:danger] = 'Retente ta chance !'
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(title: params[:gossip_title], content: params[:gossip_content], user_id: session[:user_id])
      redirect_to gossip_path(@gossip.id), success: 'Gossip validé !'
    else
      flash[:danger] = 'Retente ta chance !'
      render :edit, status: :unprocessable_entity
      flash.discard
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  def like
    @gossip = Gossip.all.find(params[:id])
    Like.create(user_id: current_user.id, gossip_id: @gossip.id)
    redirect_to root_path
  end

  private

  def check_user
    unless current_user == Gossip.find(params[:id]).user
      flash[:danger] = "Vous n'avez pas cette autorisation."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

app/helpers/city_helper.rb
# frozen_string_literal: true

module CityHelper
end

app/helpers/comment_helper.rb
# frozen_string_literal: true

module CommentHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/gossip_helper.rb
# frozen_string_literal: true

module GossipHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/session_helper.rb
module SessionHelper
  # Thurday's version without cookies
  # def current_user
  #   User.find_by(id: session[:user_id])
  # end

  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  private

  def forget(user)
    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
end

app/helpers/team_helper.rb
# frozen_string_literal: true

module TeamHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/gossip/edit.html.erb
<section class="mx-auto" style="width: 500px;">

<div class="row d-flex justify-content-around">

<!--Grid column-->
<div class="col-md-9 mb-md-0 mb-5">
<br>
<h2 class="h3-responsive font-weight-bold text-center my-4">A toi d'éditer notre potin <%= @gossip.title %></h2>
            <%= form_tag url_for(action: 'update'), method: 'patch', class: 'contact-form', id: 'contact-form' do %>        

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :gossip_title, "Annonce la couleur" %>
                          <%= text_field_tag :gossip_title , nil, class: 'form-control' , value: @gossip.title %>
                        </div>
                    </div>

                    <!--Grid column-->
                </div>

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                        <%= label_tag :gossip_content, "Ton plus grand secret " %>
                        <%= text_field_tag :gossip_content , nil, class: 'form-control', value: @gossip.content %>
                      </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                        <%= label_tag "Quelle catégorie ?" %>
                        <%= select nil, 'tag', Tag.all.collect { |t| [ t.title, t.id ] }, { include_blank: true } , class: 'form-control' %>
                        </div>
                    </div>
                </div>

            <br>

                <div class="text-center text-md-left">
                  <%= submit_tag 'Editer le potin', class: 'btn btn-primary form-control' %>
                </div>
          
                <div class="status"></div>
          <% end %>

          </section>

app/views/gossip/new.html.erb
<section class="mx-auto" style="width: 500px;">

<div class="row d-flex justify-content-around">

<!--Grid column-->
<div class="col-md-9 mb-md-0 mb-5">
<br>
<h2 class="h3-responsive font-weight-bold text-center my-4">A toi de tout nous raconter</h2>
            <%= form_tag url_for(action: 'create'), method: 'post', class: 'contact-form', id: 'contact-form' do %>        

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :gossip_title, "Annonce la couleur" %>
                          <%= text_field_tag :gossip_title , nil, class: 'form-control'%>
                        </div>
                    </div>

                    <!--Grid column-->

                </div>

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                        <%= label_tag :gossip_content, "Ton plus grand secret " %>
                        <%= text_field_tag :gossip_content , nil, class: 'form-control' %>
                      </div>
                    </div>
                </div>

                <% if false %>
                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag "Qui es tu ?" %><br>
                          <%= select nil, 'user', User.all.collect { |u| [ u.first_name, u.id ] }, { include_blank: true } , class: 'form-control' %>
                        </div>
                    </div>
                </div>
                <% end %>

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                        <%= label_tag "Quelle catégorie ?" %>
                        <%= select nil, 'tag', Tag.all.collect { |t| [ t.title, t.id ] }, { include_blank: true } , class: 'form-control' %>
                                      </div>
                    </div>
                </div>

            <br>

                <div class="text-center text-md-left">
                  <%= submit_tag 'Créer un potin', class: 'btn btn-primary form-control' %>
                </div>
          
                <div class="status"></div>
          <br>
        <% end%>
</section>

app/views/gossip/show.html.erb
    <div class="container d-flex align-middle align-items-center flex-column mt-4">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-white mb-5">
                    <h2 class="card-title font-weight-bold text-center my-4">Découvrez notre Gossip numéro <%= params[:id] %></h2>
            <div class="card-body">
                <ul class="list-unstyled">
                    <li class="position-relative booking">
                        <div class="media">
                            <div class="media-body">
                                <h5 class="mb-4"><%= @gossip.title.capitalize %>
                                <span class="badge badge-primary mx-3"></span><span class="badge badge-danger"></span></h5>
                                <div class="mb-3">
                                    <span class="mr-2 d-block d-sm-inline-block mb-2 mb-sm-0">Contribution :</span>
                                    <span class="bg-dark text-white"> <%= @gossip.user.first_name %></span>
                                </div>
                                <div class="mb-3">
                                    <span class="mr-2 d-block d-sm-inline-block mb-2 mb-sm-0">Date de création:</span>
                                    <span class="bg-dark text-white"><%= @gossip.created_at.to_datetime.strftime("%b %d, %Y") %>
                                    </span>
                                </div>

                                <div class="mb-5">
                                    <span class="mr-2 d-block d-sm-inline-block mb-1 mb-sm-0">Contenu du gossip:</span>
                                    <span class="bg-dark text-white"><%= @gossip.content %>
                                    </span>
                                </div>
                                <% if current_user %>
                                    <% if @gossip.liked?(current_user) %>
                                    <%= button_to "Like", like_path(@gossip), method: "put", disabled: true %>
                                    <% else %>
                                    <%= button_to "Like", like_path(@gossip), method: "put" %>
                                    <% end %>
                                <% end %>
                                <p class="btn btn-warning btn-outline-success btn-sm"><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                                <br>
                                <p class="btn btn-warning btn-outline-info"><%= link_to 'Profil de la commère', profile_path(@gossip.user_id) %></p>
                                <% if current_user %>
                                    <p class="btn btn-warning btn-outline-warning"><%= link_to 'Editer ce potin', edit_gossip_path(@gossip.id) %></p>
                                <% end %>
                                <p class="btn btn-warning btn-outline-warning"> <%= link_to "Effacer ce potin", gossip_path(@gossip), method: :delete, data: { confirm: "Sûr ? Votre sentence est irrévocable !" } %></p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
            </div>


    <div class="container d-flex align-middle align-items-center flex-column">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-white mb-5">
                    <h4 class="font-weight-bold text-center my-4">Découvrez les commentaires</h4>
                        <br><p class="btn btn-warning btn-outline-warning"><%= link_to 'Ecrire un commentaire', new_gossip_comment_path(@gossip.id) %></p>
                        <div class="d-flex flex-wrap justify-content-center">
                            <% @comments.each do |comment|%>
                                <div class="card border-info my-2 mx-3 border-radius rounded" style="width: 18rem;">
                                    <div class="card-body">
                                    <h5 class="card-title"><%= comment.content %></h5>
                                    <hr class="solid">
                                    <h5 class="card-title">Posté par: <%= comment.user.first_name %></h5>
                                    <p class="btn btn-outline-warning"><%= link_to 'Editer', edit_gossip_comment_path(@gossip, comment) %>
                                    <p class="btn btn-warning btn-outline-warning"> <%= link_to "Effacer ce commentaire", gossip_comment_path(@gossip, comment), method: :delete, data: { confirm: "Sûr ? Votre sentence est irrévocable !" } %></p>

                                </div>
                            </div>
                        </p>
                    <% end %>
                </div>
            </div>
        </div>
    </div>