config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'like/index'
  get 'like/show'
  get 'like/update'
  get 'like/destroy'
  get 'like/new'
  get 'like/edit'
  root to: 'home#index'
  resources :home
  resources :welcome
  resources :team
  resources :contact
  resources :gossip
  resources :profile
  resources :city
  resources :gossip do
    resources :comment
  end
  resources :session, only: %i[new create destroy]

  # ressources :like
  put '/gossip/:id/like', to: 'gossip#like', as: 'like'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def liked?(user)
    !!likes.find { |like| like.user_id == user.id }
  end
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  has_many :users
  validates :name, presence: true
  validates :zip_code, length: { is: 5 }, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/dm.rb
# frozen_string_literal: true

class Dm < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :join_user_dms
  has_many :recipients, class_name: 'User', through: :join_user_dms

  validates :content, length: { maximum: 140 }, presence: true
end

app/models/gossip.rb
# frozen_string_literal: true

class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :comments
  has_many :likes

  validates :title, length: { minimum: 3, maximum: 14 }, presence: true
  validates :content, presence: true
end

app/models/join_tag_gossip.rb
# frozen_string_literal: true

class JoinTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/join_user_dm.rb
# frozen_string_literal: true

class JoinUserDm < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :dm
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :user
  validates :user_id, uniqueness: { scope: :gossip_id }
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips

  validates :title, length: { minimum: 3, maximum: 14 }, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'Dm'
  has_many :join_user_dms
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'Dm', through: :join_user_dms
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
  has_many :comments
  has_many :likes

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, length: { maximum: 140 }, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :age, presence: true

  def name_with_initial
    "#{first_name} #{last_name}"
  end

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
  
end

app/controllers/city_controller.rb
# frozen_string_literal: true

class CityController < ApplicationController
  require 'gossip'

  def index; end

  def show
    @city = City.find(params[:id])
    @users = User.where(city_id: params[:id])
    @gossips = find_gossip(@users)
  end

  private

  def find_gossip(array)
    find_gossip = []
    array.each do |user|
      find_gossip << Gossip.find_by(user: user)
    end
    find_gossip.compact
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def update; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

app/helpers/city_helper.rb
# frozen_string_literal: true

module CityHelper
end

app/helpers/comment_helper.rb
# frozen_string_literal: true

module CommentHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/gossip_helper.rb
# frozen_string_literal: true

module GossipHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/session_helper.rb
module SessionHelper
  # Thurday's version without cookies
  # def current_user
  #   User.find_by(id: session[:user_id])
  # end

  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  private

  def forget(user)
    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
end

app/helpers/team_helper.rb
# frozen_string_literal: true

module TeamHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/city/index.html.erb
<h2 class="font-weight-bold text-center my-4">Les villes de tous les potins</h2></div>
  <div class="d-flex flex-wrap justify-content-center">
      <% City.all.each do |city|%>
        <div class="card border-info my-2 mx-3 border-radius rounded" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Ville de <%= city.name.capitalize %></h5>
            <p class="card-text">Code postal : <%= city.zip_code %></p>
            <p class="btn btn-outline-warning"><%= link_to 'Profil de la ville', city_path(city.id) %>
          </div>
        </div>
      </p>
    <% end %>
  </div>

app/views/city/show.html.erb
<div class="row d-flex justify-content-around">
  <div class="hero-unit">
    <h1>Dans l'incroyable ville de <%= @city.name %></h1>
    <p class="text-center">Il s'en passe des choses</p>
  </div>
</div>

<div class="d-flex flex-wrap justify-content-center">
  <% @gossips.each do |gossip|%>
      <div class="card border-info my-2 mx-3 border-radius rounded" style="width: 18rem;">
      <div class="card-body">
      <h5 class="card-title">Potin numéro <%= Gossip.all.index(gossip) + 1 %></h5>
      <p class="card-text">"<%= gossip.title.capitalize %>"</p>
      <p class="card-text">Contributeur : <%= User.find(gossip.user_id).first_name %></p>
      <p class="btn btn-outline-warning"><%= link_to 'Détails du potin', gossip_path(gossip.id) %>
        <% if current_user %>
        <% if gossip.liked?(current_user) %>
        <%= button_to "Like", like_path(gossip), method: "put", disabled: true %> 
        <% else %> 
        <%= button_to "Like", like_path(gossip), method: "put" %>
        <% end %> 
      <% end %>
      <p class="btn btn-warning btn-outline-success btn-sm"><%= gossip.likes.count %> <%= (gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
      </div>
      </div>
    </p>
  <% end %>
</div>