config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'like/index'
  get 'like/show'
  get 'like/update'
  get 'like/destroy'
  get 'like/new'
  get 'like/edit'
  root to: 'home#index'
  resources :home
  resources :welcome
  resources :team
  resources :contact
  resources :gossip
  resources :profile
  resources :city
  resources :gossip do
    resources :comment
  end
  resources :session, only: %i[new create destroy]

  # ressources :like
  put '/gossip/:id/like', to: 'gossip#like', as: 'like'
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  has_many :users
  validates :name, presence: true
  validates :zip_code, length: { is: 5 }, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/dm.rb
# frozen_string_literal: true

class Dm < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :join_user_dms
  has_many :recipients, class_name: 'User', through: :join_user_dms

  validates :content, length: { maximum: 140 }, presence: true
end

app/models/gossip.rb
# frozen_string_literal: true

class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :comments
  has_many :likes

  validates :title, length: { minimum: 3, maximum: 14 }, presence: true
  validates :content, presence: true
end

app/models/join_tag_gossip.rb
# frozen_string_literal: true

class JoinTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/join_user_dm.rb
# frozen_string_literal: true

class JoinUserDm < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :dm
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :user
  validates :user_id, uniqueness: { scope: :gossip_id }
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips

  validates :title, length: { minimum: 3, maximum: 14 }, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'Dm'
  has_many :join_user_dms
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'Dm', through: :join_user_dms
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
  has_many :comments
  has_many :likes

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, length: { maximum: 140 }, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :age, presence: true

  def name_with_initial
    "#{first_name} #{last_name}"
  end

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
  
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

app/helpers/city_helper.rb
# frozen_string_literal: true

module CityHelper
end

app/helpers/comment_helper.rb
# frozen_string_literal: true

module CommentHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/gossip_helper.rb
# frozen_string_literal: true

module GossipHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/session_helper.rb
module SessionHelper
  # Thurday's version without cookies
  # def current_user
  #   User.find_by(id: session[:user_id])
  # end

  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  private

  def forget(user)
    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
end

app/helpers/team_helper.rb
# frozen_string_literal: true

module TeamHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/pulse/bootstrap.min.css" integrity="sha384-L7+YG8QLqGvxQGffJ6utDKFwmGwtLcCjtwvonVZR/Ba2VzhpMwBz51GaXnUsuYbj" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark sticky-top" >
    <%= link_to "The Gossip Project", home_index_path , class: "nav-link navbar-brand" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
  <li class="nav-item active">
     <%= link_to "Accueil", home_index_path , class: "nav-link" %>
  </li>
  <li class="nav-item">
   <%= link_to "Villes", city_index_path , class: "nav-link"  %>
  </li>
  <li class="nav-item">
   <%= link_to "Utilisateurs", profile_index_path , class: "nav-link"  %>
  </li>
    <li class="nav-item">
   <%= link_to "Equipe", team_index_path , class: "nav-link"  %>
  </li>
  <li class="nav-item">
   <%= link_to "Nous contacter", contact_index_path , class: "nav-link" %>
  </li>
</ul>

<form class="form-inline my-2 my-lg-0 ">

<% if current_user %>
    <button class="btn btn-dark text-white my-2 my-sm-0"><%= link_to "Se déconnecter", session_path(:user_id), method: :delete, data: { confirm: "Prêt à vous déconnecter ?" } %></button>
<% else %>
    <button class="btn btn-dark text-white my-2 my-sm-0"><%= link_to "Se connecter", new_session_path %></button>
    <button class="btn bg-secondary  my-2 my-sm-0"><%= link_to 'Créer un compte', new_profile_path %></button>
<% end %>
  </div>
</form>

</div>
</nav>
<div class="align-self-center ">
<% flash.each do |name, msg| %>
  <div class='alert alert-<%= name %> text-center'>
  <%= msg %>
<% end %>  
</div>

<%= yield %>


  </body>
</html>